name: 'submit'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - name: Build package
        run: yarn build
      - name: Create zip
        run: yarn build:zip
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v2
        with:
          artifact: build-zip/automa-v*.zip
          keys: ${{ secrets.SUBMIT_KEYS }}
